version: '3.8'

services:
  web:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - milvus
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-app
    ports:
      - "7777:7777"
    volumes:
      - ./frontend:/app
    depends_on:
      - web

  milvus:
    image: milvusdb/milvus:v2.4.1
    container_name: milvus
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - TZ=UTC
    command: ["milvus", "run", "standalone"]
    env_file:
      - .env

  etcd:
    image: quay.io/coreos/etcd:v3.5.7
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_METRICS_URLS=http://0.0.0.0:2381
    command: etcd --advertise-client-urls http://etcd:2379 --listen-client-urls http://0.0.0.0:2379 --data-dir /etcd-data
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd-data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    env_file:
      - .env

  attu:
    image: zilliz/attu:latest
    container_name: attu
    ports:
      - "8002:8002"
    depends_on:
      - milvus
    environment:
      - MILVUS_ADDR=milvus:19530

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "6789:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  milvus_data:
  etcd_data:
  minio_data:
