apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: gerard-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.7
        ports:
        - containerPort: 2379
        env:
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_LISTEN_METRICS_URLS
          value: "http://0.0.0.0:2381"
        command: ["etcd", "--advertise-client-urls=http://etcd:2379", "--listen-client-urls=http://0.0.0.0:2379", "--data-dir=/etcd-data"]
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: gerard-v1
spec:
  ports:
  - port: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
  namespace: gerard-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
