apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-app
  namespace: gerard-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama-app
  template:
    metadata:
      labels:
        app: ollama-app
    spec:
      containers:
      - name: ollama-app
        image: your-ollama-image
        ports:
        - containerPort: 9001
        envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-app
  namespace: gerard-v1
spec:
  type: LoadBalancer
  ports:
  - port: 9001
  selector:
    app: ollama-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ollama-app-hpa
  namespace: gerard-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ollama-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
