apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gerard-v1
  name: nginx-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
