# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:13
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: password
#           POSTGRES_DB: fastapi_db
#         ports:
#           - 5432:5432

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9

#       - name: Install dependencies
#         run: |
#           cd backend
#           python -m venv venv
#           source venv/bin/activate
#           pip install -r requirements.txt

#       - name: Run tests
#         run: |
#           cd backend
#           source venv/bin/activate
#           # pytest

#       - name: Build and push Docker images
#         run: |
#           docker-compose build
#           # docker-compose push

#  Disabling this as git workflow is out of memory